### ISSUE TITLE
missing Libs

### ISSUE THREAD

**Issue by Qcat0214** [coryo/PallyPower#2]
Now there's a error when only PP is loaded into the game, the reason should be the lack of dependency libs

Message: ...\AddOns\PallyPower\libs\LibClassicDurations\core.lua:68: Cannot find a library instance of "CallbackHandler-1.0".
Time: Thu Sep 19 14:20:10 2019
Count: 1

**Comment by coryo** [comment]
it should be included now. I had it loading with another addon and didn't notice.

**Comment by Qcat0214** [comment]
yea, it's all good now, ty!
