### ISSUE TITLE
Warriors kinda need Salv

### ISSUE THREAD

**Issue by Xtreeem** [coryo/PallyPower#3]
Given the amount of dps warriors present in classic, it would probably make sense to unlock salvation for warriors, even if the tanks have to manually click it off.

**Comment by coryo** [comment]
The 'smart buffs' option disables some buffs for some classes.  I guess the original design was done at a time when people didn't salv dps warriors?  Just disable that setting in the options and I'll make it disable by default.

You can also shift+click to assign buffs to all classes which also bypasses that 'feature'.
