### ISSUE TITLE
[RU localization]

### ISSUE THREAD

**Issue by wowzhoe** [coryo/PallyPower#6]
addon needs russian localization, i can help you with that

**Comment by coryo** [comment]
yeah that would be cool.  evereything you need should be in localization.lua

**Comment by wowzhoe** [comment]
remote: Permission to coryo/PallyPower.git denied to wowzhoe.
fatal: unable to access 'https://github.com/coryo/PallyPower.git/': The requested URL returned error: 403
Cant push my branch

**Comment by coryo** [comment]
You'll have to do it through a pull request.
