### ISSUE TITLE
Game seems to not be able to locate the addon. 

### ISSUE THREAD

**Issue by Marglib** [coryo/PallyPower#7]
Potentially something with Elvui? Seems like the pally power just does not load - Only difference I can find in comparison with other people using it, is that I  am using Elvui.

**Comment by plutonium447** [comment]
I am also using elvui, but i have not had any issue using the addon.
Have you removed the -master from the end of the folder name? and the folder name is exactly `PallyPower`?
let me know how you go

**Comment by Marglib** [comment]
Yeah I have removed the master from the end. Not sure what went wrong, but somehow it worked after I rebooted my computer.
